# Generated by Django 6.0.6 on 2026-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_communitypost_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('COMMUNITY_INVITE', 'Community Invite'), ('TRIP_REQUEST', 'Trip Request'), ('TRIP_ACCEPTED', 'Trip Accepted'), ('COMMENT', 'Comment'), ('LIKE', 'Like'), ('MESSAGE', 'Message'), ('ADMIN_ANNOUNCEMENT', 'Admin Announcement'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
